# Generated by Django 5.0.4 on 2024-04-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraiser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
